version: "3.9"

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro

