services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # (optioneel) websockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"   # Node-RED web UI
    volumes:
      - ./nodered/data:/data
    networks:
      - proxy

networks:
  proxy:
    external: true
